{{- if .Values.deploymentConfig }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "tv-submit.fullname" . }}
  labels:
    {{- include "tv-submit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.min }}
  revisionHistoryLimit: 10
  selector:
    {{- include "tv-submit.selectorLabels" . | nindent 4 }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
        rollme: {{ randAlphaNum 5 | quote }}
      creationTimestamp: null
      labels:
        {{- include "tv-submit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP
              value: "tv-cluster-kafka-bootstrap:9092"
          image: ''
          imagePullPolicy: Always
          name: {{ include "tv-submit.name" . }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - {{ include "tv-submit.name" . }}
        from:
          kind: ImageStreamTag
          name: {{ include "tv-submit.fullname" . }}:{{ .Values.image_version }}
        lastTriggeredImage: ""
      type: ImageChange
{{- end }}
